theme: jekyll-theme-giellalt
title: Dictionary for North Saami ⇒ Lule Saami
description: An electronic dictionary from North Saami to Lule Saami

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
